### PR TITLE
Fix log filtering

### LINKED ISSUE #11141: [4.x]: Logs with web.WARNING when devMode is disabled
### What happened?

With `devMode` enabled, you normally get these lines for each page load in the log files:

```
2022-05-07 14:01:11 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=craft40;port=3306 {"memory":1604768}                                                                  
2022-05-07 14:01:11 [web.INFO] [yii\web\Session::open] Session started {"memory":2396792}                                                                                                                         
2022-05-07 14:01:11 [web.INFO] [application] Request context:
```

But when you disable `devMode`, you get a single `web.WARNING` line for each page load:

```
2022-05-07 14:06:21 [web.WARNING] [application] Request context:
```

Should this line be a `web.INFO` when `devMode` is disabled ?

### Craft CMS version

4.0.1

### PHP version

8.0.18

### Operating system and version

Darwin 21.4.0

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-30)

### Installed plugins and versions

No plugins

### PR DESCRIPTION
**Pull request by timkelty**
- Fixes empty trace filtering
- Fixes #11141

### CODE REVIEW

File: src/log/MonologTarget.php [hunk 1]
```diff
@@ -154,6 +156,28 @@ protected function getContextMessage(): string
...
+     */
+    private function _filterMessagesByPsrLevel(array $messages, string $level): array
+    {
+        $levelMap = Collection::make((array) $this->getLevels());
+        $monologLevel = Logger::toMonologLevel($level);
+        $messages = Collection::make($messages)
+            ->filter(function($message) use ($levelMap, $monologLevel) {
+                $level = $message[1];
+
+                /** @phpstan-var LogLevel::* $psrLevel */
```
Comment (timkelty) [inline src/log/MonologTarget.php:172]: Can't figure out why this doesn't seem to appease PHPStan…
