### PR TITLE
Fix logic flaw in new user save

### LINKED ISSUE #10661: Double-click on register form creates multiple users with the same email address
### Description

We noticed some duplicate user accounts appearing that were being created at the same time and managed to have the same email address.

If I use our public registration form to create a new account using an email address that _already exists_, the form validation returns false and I'm told a user already exists with that email.

However, if I try to create a new account using an email address that doesn't exist, and I double click the form's submit button, two accounts are created.

Screenshot 2022-03-02 at 10 03 06

The only other Github issue I've found that might be related is #9835

### Steps to reproduce

1. Follow the steps in [this knowledge base guide](https://craftcms.com/knowledge-base/front-end-user-accounts) to allow public registrations and create a frontend registration form
2. Double-click the form's submit button to submit the form twice successively

### Additional info

- Craft version: 3.7.35
- PHP version: 7.4.26
- Database driver & version: mysql 5.7

### PR DESCRIPTION
**Pull request by timkelty**
### Related issues
Fixes #10661, #9835

### CODE REVIEW

File: src/controllers/UsersController.php [hunk 1]
```diff
@@ -1245,10 +1245,9 @@ public function actionSaveUser()
         }
 
         // Manually validate the user so we can pass $clearErrors=false
-        if (
-            !$user->validate(null, false) ||
-            !Craft::$app->getElements()->saveElement($user, false)
-        ) {
```
Comment (timkelty) [inline src/controllers/UsersController.php:1251]: The way it was, it would call saveElement (w/ validation) when `validate` failed.
