### PR TITLE
Fix asset controller responses

### LINKED ISSUE #12158: [4.x]: AssetsController always returns 200
### Description
A couple spots in `AssetsController` return 200s with `error` and `success: true`.

They should use `asModelFailure` and `asSuccess`, and the JS updated to properly catch and not rely on `error`/`success` keys.

### Craft CMS version

4.2.8

### PHP version

_No response_

### Operating system and version

_No response_

### Database type and version

_No response_

### Image driver and version

_No response_

### Installed plugins and versions

-

### PR DESCRIPTION
**Pull request by timkelty**
These cases were missed when we normalized proper js response handling in the 4.0 release.

### TODO
- [x] Update JS

### Related issues
- Fixes #12158

### CODE REVIEW

File: src/controllers/AssetsController.php [hunk 1]
```diff
@@ -313,8 +313,7 @@ public function actionUpload(): Response
 
         // In case of error, let user know about it.
         if (!$result) {
-            $errors = $asset->getFirstErrors();
-            return $this->asFailure(implode("\n", $errors));
+            return $this->asModelFailure($asset);
         }
```
Comment (timkelty) [inline src/controllers/AssetsController.php:317]: Return model errors, and let the JS build the message string.

File: src/controllers/RebrandController.php [hunk 2]
```diff
@@ -102,7 +102,7 @@ public function actionDeleteSiteImage(): ?Response
         $type = $this->request->getRequiredBodyParam('type');
 
         if (!in_array($type, $this->_allowedTypes, true)) {
-            $this->asFailure(Craft::t('app', 'That is not an allowed image type.'));
+            return $this->asFailure(Craft::t('app', 'That is not an allowed image type.'));
         }
```
Comment (timkelty) [inline src/controllers/RebrandController.php:106]: Pretty sure this is just a boo-boo from the initial conversion.

File: src/web/assets/cp/src/js/AssetSelectInput.js [hunk 3]
```diff
@@ -268,51 +267,51 @@ Craft.AssetSelectInput = Craft.BaseElementSelectInput.extend({
...
-          alert(response.data.message);
-        });
-
-      Craft.cp.runQueue();
-    }
+      .catch(({response}) => {
+        alert(response.data.message);
+      });
+
+    Craft.cp.runQueue();
```
Comment (timkelty) [inline src/web/assets/cp/src/js/AssetSelectInput.js:295]: Just unwrapping/removing the `data.result.error` condition.

File: src/web/assets/cp/src/js/AssetSelectInput.js [hunk 4]
```diff
@@ -268,51 +267,51 @@ Craft.AssetSelectInput = Craft.BaseElementSelectInput.extend({
...
-      message = filename
-        ? Craft.t('app', 'Upload failed for “{filename}”.', {filename})
-        : Craft.t('app', 'Upload failed.');
+      if (errorMessages.length) {
+        message = errorMessages.join('\n');
+      } else if (filename) {
+        message = Craft.t('app', 'Upload failed for “{filename}”.', {filename});
+      } else {
+        message = Craft.t('app', 'Upload failed.');
+      }
```
Comment (timkelty) [inline src/web/assets/cp/src/js/AssetSelectInput.js:314]: Same logic as above :(

File: src/web/assets/cp/src/js/ImageUpload.js [hunk 5]
```diff
@@ -128,12 +124,23 @@ Craft.ImageUpload = Garnish.Base.extend(
...
+        if (errorMessages.length) {
+          message = errorMessages.join('\n');
+        } else if (filename) {
+          message = Craft.t('app', 'Upload failed for “{filename}”.', {
+            filename,
+          });
+        } else {
+          message = Craft.t('app', 'Upload failed.');
+        }
       }
```
Comment (timkelty) [inline src/web/assets/cp/src/js/ImageUpload.js:144]: Looking familiar?

**Review by timkelty — COMMENTED** [review]
Apart from the obvious question of "why is the same code in so many places", just looking for another set of eyes, as my js-fu is rusty.
